//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.2.0
//     from Assets/Temp/MigTempActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @MigTempActions : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @MigTempActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""MigTempActions"",
    ""maps"": [
        {
            ""name"": ""MigTestMap"",
            ""id"": ""5b6a2eb2-883e-4191-abc5-2085b342d2ef"",
            ""actions"": [
                {
                    ""name"": ""Grab"",
                    ""type"": ""Button"",
                    ""id"": ""f826acb2-547c-44d4-bdbf-5f00478d8c7a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""f30bb172-2ffa-4f47-bd09-ca7b8f19c97b"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Grab"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // MigTestMap
        m_MigTestMap = asset.FindActionMap("MigTestMap", throwIfNotFound: true);
        m_MigTestMap_Grab = m_MigTestMap.FindAction("Grab", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // MigTestMap
    private readonly InputActionMap m_MigTestMap;
    private IMigTestMapActions m_MigTestMapActionsCallbackInterface;
    private readonly InputAction m_MigTestMap_Grab;
    public struct MigTestMapActions
    {
        private @MigTempActions m_Wrapper;
        public MigTestMapActions(@MigTempActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Grab => m_Wrapper.m_MigTestMap_Grab;
        public InputActionMap Get() { return m_Wrapper.m_MigTestMap; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(MigTestMapActions set) { return set.Get(); }
        public void SetCallbacks(IMigTestMapActions instance)
        {
            if (m_Wrapper.m_MigTestMapActionsCallbackInterface != null)
            {
                @Grab.started -= m_Wrapper.m_MigTestMapActionsCallbackInterface.OnGrab;
                @Grab.performed -= m_Wrapper.m_MigTestMapActionsCallbackInterface.OnGrab;
                @Grab.canceled -= m_Wrapper.m_MigTestMapActionsCallbackInterface.OnGrab;
            }
            m_Wrapper.m_MigTestMapActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Grab.started += instance.OnGrab;
                @Grab.performed += instance.OnGrab;
                @Grab.canceled += instance.OnGrab;
            }
        }
    }
    public MigTestMapActions @MigTestMap => new MigTestMapActions(this);
    public interface IMigTestMapActions
    {
        void OnGrab(InputAction.CallbackContext context);
    }
}
